import { createFileRoute } from "@tanstack/react-router";
import { ChevronLeft, ChevronRight, Check, CircleDollarSign, Camera, Package, Sparkles } from "lucide-react";
import coverImage from "@/assets/morango-cravejado-cover.jpg";
import detailImage from "@/assets/morango-cravejado-detail.jpg";
import packagingImage from "@/assets/morango-cravejado-packaging.jpg";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Morango Cravejado | Guia Premium" }, { name: "description", content: "Guia completo para preparar, precificar e vender Morango Cravejado." },
    { property: "og:title", content: "Morango Cravejado | Guia Premium" }, { property: "og:description", content: "Prepare, precifique e venda o doce que virou tendência." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ] }), component: Ebook,
});

type Page = { section: string; title: string; lead?: string; type?: "impact" | "recipe" | "list" | "table" | "image"; items?: string[] };
const pages: Page[] = [
  { section: "Parte 1 · O Produto", title: "O que é o Morango Cravejado", lead: "Uma releitura sofisticada: morango fresco envolto em brigadeiro branco, banhado em chocolate e finalizado com cristais de caramelo vermelho.", type: "image" },
  { section: "Capítulo 1", title: "Cravejado não é Morango do Amor", lead: "No Morango Cravejado, o caramelo não forma uma casca inteira. Ele é quebrado em fragmentos e aplicado como acabamento, criando brilho, textura e identidade visual.", items: ["Morango do Amor: cobertura contínua e lisa.", "Morango Cravejado: chocolate cremoso + cristais crocantes.", "Resultado: aparência artesanal, rica e presenteável."] },
  { section: "Capítulo 2", title: "Por que ele chama tanta atenção", lead: "O contraste entre o vermelho, o branco e o brilho dos cristais faz o produto se destacar na vitrine e no conteúdo digital.", type: "list", items: ["Visual que convida ao close", "Venda unitária ou em kits", "Presenteável em datas especiais", "Texturas que rendem vídeos curtos"] },
  { section: "Capítulo 3", title: "Sua bancada essencial", type: "list", items: ["Panela de fundo grosso", "Espátula de silicone", "Balança digital", "Termômetro culinário", "Papel manteiga", "Recipientes secos", "Garfo ou pinça para banho", "Embalagens e forminhas"] },
  { section: "Capítulo 4", title: "Ingredientes", type: "list", items: ["BRIGADEIRO BRANCO · leite condensado, creme de leite, manteiga e chocolate branco.", "CARAMELIZADO CROCANTE · açúcar, água e corante alimentício vermelho em gel.", "MONTAGEM · morangos firmes e secos.", "FINALIZAÇÃO · cobertura de chocolate de boa qualidade."] },
  { section: "Parte 2 · Como Preparar", title: "Brigadeiro Branco", type: "recipe", lead: "A camada cremosa que protege o morango e entrega uma mordida macia.", items: ["INGREDIENTES · 1 leite condensado, 100 g de chocolate branco, 1 colher de manteiga e ½ caixa de creme de leite.", "PREPARO · cozinhe em fogo baixo, mexendo sempre, até soltar do fundo.", "PONTO IDEAL · massa firme, lisa e ainda moldável depois de fria.", "DICA · cubra com filme em contato e resfrie antes de usar."] },
  { section: "Capítulo 6", title: "O ponto que muda tudo", type: "table", items: ["Muito mole · escorre e não sustenta o morango.", "Ideal · modela com facilidade e segura a fruta.", "Muito firme · racha ao envolver e perde delicadeza."] },
  { section: "Capítulo 7", title: "Morangos preparados", lead: "Selecione frutas firmes e bonitas. Higienize, escorra e seque uma a uma com cuidado. Qualquer excesso de umidade reduz a aderência e encurta a conservação.", type: "image" },
  { section: "Capítulo 8", title: "Caramelo Crocante", type: "recipe", items: ["INGREDIENTES · açúcar, água e corante vermelho em gel.", "PREPARO · leve ao fogo sem mexer até atingir cor rubi e ponto de caramelo.", "RESFRIAMENTO · despeje em papel manteiga untado e deixe endurecer.", "CRISTAIS · quebre em pedaços irregulares quando estiver totalmente frio."] },
  { section: "Capítulo 9", title: "Cristais que parecem joias", lead: "Busque variação de tamanhos: pequenos fragmentos preenchem espaços; peças médias dão textura. Evite pedaços pontiagudos demais ou grandes a ponto de desequilibrar o doce." },
  { section: "Capítulo 10", title: "Montagem do Morango Cravejado", type: "list", items: ["01 · Envolva o morango seco no brigadeiro.", "02 · Resfrie até firmar.", "03 · Banhe em chocolate.", "04 · Aplique os cristais enquanto a cobertura está fresca.", "05 · Finalize com limpeza e simetria.", "06 · Embale apenas quando estiver firme."] },
  { section: "Capítulo 11", title: "O acabamento que vende", type: "image", lead: "A apresentação é parte da receita: cristais bem distribuídos, brilho uniforme, tamanho equilibrado e uma base limpa transformam produção em produto premium." },
  { section: "Capítulo 12", title: "Variações com intenção", items: ["Chocolate branco ou ao leite", "Caramelo em tons vermelhos ou rosados", "Caixas para presente", "Edições premium e kits"], type: "list" },
  { section: "Parte 3 · Transformar em Negócio", title: "Ficha técnica", type: "table", items: ["Peso do morango · ____ g", "Peso do brigadeiro · ____ g", "Peso do chocolate · ____ g", "Peso do caramelo · ____ g", "Peso final · ____ g", "Rendimento e validade · ______"] },
  { section: "Capítulo 14", title: "Conheça o custo real", type: "impact", lead: "CUSTO DOS INGREDIENTES + EMBALAGEM + GASTOS DE PRODUÇÃO + MÃO DE OBRA = CUSTO REAL" },
  { section: "Exemplo ilustrativo", title: "Do custo ao preço", type: "table", items: ["Ingredientes por unidade · R$ 4,20", "Embalagem · R$ 1,30", "Produção e mão de obra · R$ 2,50", "Custo real · R$ 8,00", "Preço de referência editável · R$ 16,00"] },
  { section: "Capítulo 15", title: "Como definir o preço", lead: "Preço nasce do seu custo, da margem desejada e do posicionamento. Embalagem, acabamento e facilidade de compra aumentam a percepção de valor. Valores são sempre referências: adapte à sua realidade.", type: "list", items: ["Custo", "Margem", "Posicionamento", "Concorrência local", "Embalagem", "Percepção de valor"] },
  { section: "Capítulo 16", title: "Preço baixo não significa venda fácil.", type: "impact", lead: "Cobrar pouco pode consumir sua margem, reduzir a percepção de valor e tornar o negócio cansativo. Venda com clareza, qualidade e cálculo." },
  { section: "Capítulo 17", title: "Embalagem é convite", type: "image", lead: "Unidade bem apresentada, caixa com 2 ou 4, caixa presenteável e kits especiais: escolha embalagens que protejam o produto e reforcem sua proposta." },
  { section: "Capítulo 18", title: "Aumente o ticket médio", type: "list", items: ["Ofereça caixas com 2, 4 e 6 unidades.", "Crie combos para presentes e datas comemorativas.", "Sugira adicionais que façam sentido.", "Apresente a caixa premium como uma escolha especial."] },
  { section: "Parte 4 · Marketing e Vendas", title: "Instagram que dá vontade de comprar", type: "image", lead: "Aproxime a câmera: mostre o corte, a textura, o caramelo quebrando, o brilho do chocolate e os bastidores de uma produção cuidadosa." },
  { section: "Capítulo 20", title: "Ideias para Reels", type: "list", items: ["“Você já viu esse morango?”", "“Olha o que acontece quando eu quebro essa casquinha…”", "“Do morango comum ao Morango Cravejado.”", "“Quanto custa fazer um Morango Cravejado?”"] },
  { section: "Capítulo 21", title: "Fotografia que vende", lead: "Use luz natural indireta, fundo limpo e enquadramentos próximos. A macro revela textura; a composição revela cuidado. Faça a imagem parecer tão gostosa quanto o doce.", type: "image" },
  { section: "Capítulo 22", title: "Venda pelo WhatsApp", type: "list", items: ["Cliente demonstra interesse", "Apresente opções e fotos", "Informe o preço", "Confirme pedido e pagamento", "Combine retirada ou entrega"] },
  { section: "Capítulo 23", title: "Mensagem de venda", type: "recipe", items: ["ABERTURA · “Oi! Tenho Morango Cravejado fresquinho para encomenda.”", "OPÇÕES · “Você prefere unidade ou caixa para presente?”", "FECHAMENTO · “Posso separar sua caixa para [dia/horário]?”", "CONFIRMAÇÃO · “Pedido confirmado! Obrigada por escolher meu trabalho.”"] },
  { section: "Capítulo 24", title: "Combos e ofertas", type: "table", items: ["1 unidade · R$ ___", "Caixa com 2 · R$ ___", "Caixa com 4 · R$ ___", "Caixa com 6 · R$ ___", "Caixa presente · R$ ___", "EXEMPLOS EDITÁVEIS · adapte ao seu custo real"] },
  { section: "Capítulo 25", title: "Produção sob encomenda", lead: "Defina antecedência, quantidade mínima, horários de retirada e regras de entrega. Produzir por pedido ajuda a preservar a qualidade, evitar desperdício e organizar sua agenda." },
  { section: "Capítulo 26", title: "Controle financeiro", type: "table", items: ["Data | Pedidos | Quantidade", "Faturamento | Custos | Lucro", "____ | ____ | ____", "____ | ____ | ____", "____ | ____ | ____"] },
  { section: "Capítulo 27", title: "Plano de lançamento em 7 dias", type: "list", items: ["DIA 1 · Apresentação", "DIA 2 · Bastidores", "DIA 3 · Produto", "DIA 4 · Prova social", "DIA 5 · Oferta", "DIA 6 · Urgência", "DIA 7 · Últimas encomendas"] },
  { section: "Capítulo 28", title: "Checklist de produção", type: "list", items: ["Morangos selecionados e secos", "Brigadeiro no ponto", "Caramelo quebrado", "Cobertura preparada", "Embalagens prontas", "Produtos refrigerados corretamente"] },
  { section: "Capítulo 29", title: "Checklist de venda", type: "list", items: ["Fotos atualizadas", "Cardápio e preços revisados", "Prazos informados", "Pagamento confirmado", "Retirada ou entrega registrada", "Pós-venda realizado"] },
  { section: "Capítulo 30 · Bônus", title: "Seu repertório para vender", type: "list", items: ["Posts: textura, bastidor, embalagem e corte.", "Frases: “feito para presentear e desejar”.", "Reels: transformação, quebra, montagem e entrega.", "Combos: experimente criar opções para cada ocasião."] },
];

function Ebook() { const go = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); return <main className="pb-8"><nav className="screen-nav sticky top-0 z-20 border-b border-border bg-background/95 px-5 py-3 backdrop-blur"><div className="mx-auto flex max-w-[794px] items-center justify-between"><button onClick={() => go("sumario")} className="text-xs font-bold uppercase tracking-[.16em] text-primary">Sumário</button><span className="font-display text-lg text-primary">Morango Cravejado</span><button onClick={() => window.print()} className="text-xs font-bold uppercase tracking-[.16em] text-primary">Imprimir</button></div></nav>
<section id="capa" className="book-page editorial-page flex flex-col justify-between"><div><p className="eyebrow">Ebook gourmet · edição premium</p><div className="gold-rule mt-7" /><h1 className="book-title mt-8 text-6xl text-primary sm:text-8xl">MORANGO<br />CRAVEJADO</h1><p className="mt-7 max-w-sm text-sm font-medium leading-7 text-foreground">O guia completo para preparar, precificar e vender o doce que virou tendência</p></div><img src={coverImage} alt="Morango cravejado gourmet coberto por cristais vermelhos" width={1200} height={1600} className="absolute inset-x-0 bottom-0 h-[56%] w-full object-cover" /><div className="relative z-10 mt-auto bg-card/88 p-5 backdrop-blur-sm"><p className="text-xs uppercase tracking-[.18em] text-gold">Receita · processo · negócio</p></div></section>
<section id="sumario" className="book-page editorial-page"><p className="eyebrow">Navegação</p><h2 className="book-title mt-5 text-5xl text-primary">Sumário</h2><div className="mt-12 grid gap-8">{[["PARTE 1", "O Produto", 1, 5],["PARTE 2", "Como Preparar", 6, 13],["PARTE 3", "Como Transformar em Negócio", 14, 20],["PARTE 4", "Marketing e Vendas", 21, 32]].map(([part, name, start, end]) => <button key={String(part)} onClick={() => go(`pagina-${start}`)} className="flex items-end justify-between border-b border-border pb-4 text-left"><span><span className="block text-xs font-bold tracking-[.16em] text-gold">{part}</span><span className="book-title mt-2 block text-3xl text-primary">{name}</span></span><span className="text-sm text-muted-foreground">{start}—{end}</span></button>)}</div><p className="absolute bottom-20 max-w-sm text-sm leading-6 text-muted-foreground">Toque em uma parte para começar. Use a navegação entre as páginas para seguir no seu ritmo.</p><span className="page-number">2</span></section>
{pages.map((page, index) => <BookPage key={page.title} page={page} number={index + 3} image={index === 10 || index === 22 ? detailImage : index === 18 ? packagingImage : undefined} />)}
<section className="book-page editorial-page flex flex-col justify-center text-center"><p className="eyebrow">O seu próximo passo</p><div className="gold-rule mx-auto mt-7" /><h2 className="book-title mt-10 text-5xl text-primary">APRENDA.<br />PADRONIZE.<br />PRECIFIQUE.<br />VENDA.</h2><p className="mx-auto mt-10 max-w-sm text-sm leading-7 text-muted-foreground">Comece com cuidado, ajuste com prática e apresente seu trabalho com a segurança de quem conhece o próprio valor.</p><span className="page-number">35</span></section></main> }

function BookPage({ page, number, image }: { page: Page; number: number; image?: string | undefined }) { const id = `pagina-${number - 2}`; const Icon = page.section.includes("Marketing") ? Camera : page.section.includes("Negócio") ? CircleDollarSign : page.type === "list" ? Check : page.type === "image" ? Sparkles : Package; return <><section id={id} className={`book-page editorial-page ${page.type === "impact" ? "flex flex-col justify-center text-center" : ""}`}><div className="relative z-10"><p className="eyebrow">{page.section}</p>{page.type === "impact" && <div className="gold-rule mx-auto mt-8" />}<h2 className="book-title mt-5 text-4xl text-primary sm:text-5xl">{page.title}</h2>{image && <img src={image} alt="Morango cravejado gourmet" loading="lazy" width={1600} height={1104} className="mt-8 aspect-[4/3] w-full object-cover" />}{page.lead && <p className="mt-7 max-w-xl text-sm leading-7 text-muted-foreground">{page.lead}</p>}{page.items && <div className={`mt-8 ${page.type === "table" ? "border-y border-gold" : "grid gap-3"}`}>{page.items.map((item, i) => <div key={item} className={page.type === "table" ? "border-b border-border py-4 text-sm font-medium last:border-0" : "flex items-start gap-3 text-left text-sm leading-6"}>{page.type !== "table" && <Icon size={15} className="mt-1 shrink-0 text-gold" />}<span>{item}</span>{page.type === "table" && <span className="float-right font-display text-gold">{String(i + 1).padStart(2, "0")}</span>}</div>)}</div>}</div><span className="page-number">{number}</span></section><div className="book-navigation"><button onClick={() => document.getElementById(number === 3 ? "sumario" : `pagina-${number - 3}`)?.scrollIntoView({ behavior: "smooth" })}><ChevronLeft className="mr-1 inline" size={14} /> Voltar</button><button onClick={() => document.getElementById(number === 34 ? "capa" : `pagina-${number - 1}`)?.scrollIntoView({ behavior: "smooth" })}>{number === 34 ? "Voltar ao início" : "Próximo"} <ChevronRight className="ml-1 inline" size={14} /></button></div></> }